version: '2.0'
services:
  web:
    restart: always
    image: nginx:1.14-alpine
    volumes:
      - .:/etc/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
      - "8443:443"
